### PR TITLE
Shared state aggreate functions and first/last

### PR DESCRIPTION
**Pull request by msqr**
This PR addresses #10 and #11 and #12 all in one.

### CODE REVIEW

**Comment by pjungwir** [comment]
Thanks! I pushed a commit to the same branch in my own repo fixing some compiler warnings. Would you merge that in?

Also it looks like there is a failing test for `vec_div`:

```
diff -U3 /home/paul/src/aggs_for_vecs/expected/vec_div.out /home/paul/src/aggs_for_vecs/results/vec_div.out
--- /home/paul/src/aggs_for_vecs/expected/vec_div.out	2021-12-27 12:49:54.559136629 -0800
+++ /home/paul/src/aggs_for_vecs/results/vec_div.out	2021-12-27 13:05:23.446578385 -0800
@@ -259,15 +259,15 @@
 
 -- numeric div to scalar 0 rhs
 SELECT r, pg_typeof(r) FROM (SELECT vec_div(nums, 0::numeric) FROM measurements WHERE sensor_id IN (4)) r(r);
-       r        | pg_typeof 
-----------------+-----------
- {NaN,NULL,NaN} | numeric[]
+            r             | pg_typeof 
+--------------------------+-----------
+ {Infinity,NULL,Infinity} | numeric[]
 (1 row)
 
 -- numeric div to array 0
 SELECT r, pg_typeof(r) FROM (SELECT vec_div(nums, ARRAY[0,0,1]::numeric[]) FROM measurements WHERE sensor_id IN (4)) r(r);
-               r               | pg_typeof 
--------------------------------+-----------
- {NaN,NULL,2.3400000000000000} | numeric[]
+                 r                  | pg_typeof 
+------------------------------------+-----------
+ {Infinity,NULL,2.3400000000000000} | numeric[]
 (1 row)
 
```

Any thoughts on that?

**Comment by pjungwir** [comment]
Actually both problems pre-date this PR, so I've merged it. I'll apply my fix for the warnings. I'll work on the failing test too, but if you fix it yourself let me know.

**Comment by pjungwir** [comment]
Looks like the `vec_div` problem was because we return `Infinity` on pg 14 when dividing by zero, but `NaN` on earlier versions.

**Comment by msqr** [comment]
Yes, sorry I forgot to add the expectation for PG 14. I'm away for a couple of weeks, so can look at that when I return, if you didn't already address it.

**Comment by pjungwir** [comment]
I fixed it already. I found the var samp problem too! I think everything is set to release version 1.3.0; I hope to do that this week.

I hope you enjoy your travels!

**Pull request merged**
